export type Vegetable = {
  id: string;
  name: string;
  tamilName: string; // Added for Tamil support
  image: string;
  price: number;
  origin: string;
  selected?: boolean;
};

export const SOUTHERN_VEGETABLES: Vegetable[] = [
  {
    id: "1",
    name: "Green Chilli",
    tamilName: "பச்சை மிளகாய்",
    image: "local://Chilli.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "2",
    name: "Tomato",
    tamilName: "தக்காளி",
    image: "local://Tomato.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "3",
    name: "Onion",
    tamilName: "வெங்காயம்",
    image: "local://Onion.png",
    price: 45,
    origin: "Southern States",
  },
  {
    id: "4",
    name: "Potato",
    tamilName: "உருளை",
    image: "local://Potato.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "5",
    name: "Carrot",
    tamilName: "கேரட்",
    image: "local://Carrot.png",
    price: 60,
    origin: "Southern States",
  },
  {
    id: "6",
    name: "Green Beans",
    tamilName: "பீன்ஸ்",
    image: "local://Beans.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "7",
    name: "Broad Beans",
    tamilName: "அவரை",
    image: "local://Beans.png", // Using Beans.png as fallback
    price: 55,
    origin: "Southern States",
  },
  {
    id: "8",
    name: "Radish",
    tamilName: "முள்ளங்கி",
    image: "local://Raddish.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "9",
    name: "Ginger",
    tamilName: "இஞ்சி",
    image: "local://Ginger.png",
    price: 120,
    origin: "Southern States",
  },
  {
    id: "10",
    name: "Brinjal (Eggplant)",
    tamilName: "கத்திரிக்காய்",
    image: "local://Brinjal.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "11",
    name: "Drumstick (Moringa)",
    tamilName: "முருங்கைக்காய்",
    image: "local://Drumstick.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "12",
    name: "Raw Mango",
    tamilName: "மாங்காய்",
    image: "local://RawMango.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "13",
    name: "Cabbage",
    tamilName: "கோஸ்",
    image: "local://Cabbage.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "14",
    name: "Cauliflower",
    tamilName: "காலிப்ளவர்",
    image: "local://Cauliflower.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "15",
    name: "Bottle Gourd",
    tamilName: "சொரைக்காய்",
    image: "local://BottleGourd.png",
    price: 35,
    origin: "Southern States",
  },
  {
    id: "16",
    name: "Snake Gourd",
    tamilName: "புடலங்காய்",
    image: "local://Snake Gourd.png",
    price: 35,
    origin: "Southern States",
  },
  {
    id: "17",
    name: "Elephant Foot Yam",
    tamilName: "கருணை கிழங்கு",
    image: "local://Elephant.png",
    price: 60,
    origin: "Southern States",
  },
  {
    id: "18",
    name: "Taro Root",
    tamilName: "பிடிக்கருணை",
    image: "local://Taro Root.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "19",
    name: "Colocasia",
    tamilName: "சேப்பங்கிழங்கு",
    image: "local://Taro Root.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "20",
    name: "Lady's Finger (Okra)",
    tamilName: "வெண்டைக்காய்",
    image: "local://Lady's Finger.png",
    price: 35,
    origin: "Southern States",
  },
  {
    id: "21",
    name: "Bitter Gourd",
    tamilName: "பாகற்காய்",
    image: "local://BitterGourd.png",
    price: 45,
    origin: "Southern States",
  },
  {
    id: "22",
    name: "Ridge Gourd",
    tamilName: "பீர்க்கங்காய்",
    image: "local://RidgeGourd.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "23",
    name: "Ash Gourd",
    tamilName: "வெள்ளை பூசணி",
    image: "local://AshGourd.png",
    price: 30,
    origin: "Southern States",
  },
  {
    id: "24",
    name: "Pumpkin",
    tamilName: "மஞ்சள் பூசணி",
    image: "local://Pumpkin.png",
    price: 25,
    origin: "Southern States",
  },
  {
    id: "25",
    name: "Chow Chow",
    tamilName: "சௌ சௌ",
    image: "local://ChowChow.png",
    price: 35,
    origin: "Southern States",
  },
  {
    id: "26",
    name: "Beetroot",
    tamilName: "பீட்ரூட்",
    image: "local://Beetroot.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "27",
    name: "Garlic",
    tamilName: "பூண்டு",
    image: "local://Garlic.png",
    price: 250,
    origin: "Southern States",
  },
  {
    id: "28",
    name: "Lemon",
    tamilName: "எலுமிச்சை",
    image: "local://Lemon.png",
    price: 5, // Price per piece typically
    origin: "Southern States",
  },
  {
    id: "29",
    name: "Curry Leaves",
    tamilName: "கறிவேப்பிலை",
    image: "local://CurryLeaves.png",
    price: 10, // Per bundle
    origin: "Southern States",
  },
  {
    id: "30",
    name: "Coriander",
    tamilName: "கொத்தமல்லி",
    image: "local://Coriander.png",
    price: 15, // Per bundle
    origin: "Southern States",
  },
  {
    id: "31",
    name: "Mint",
    tamilName: "புதினா",
    image: "local://Mint.png",
    price: 10, // Per bundle
    origin: "Southern States",
  },
  {
    id: "32",
    name: "Cluster Beans",
    tamilName: "கொத்தவரங்காய்",
    image: "local://Beans.png",
    price: 40,
    origin: "Southern States",
  },
  {
    id: "33",
    name: "Yams (Small)",
    tamilName: "சேனை கிழங்கு",
    image: "local://Elephant.png",
    price: 50,
    origin: "Southern States",
  },
  {
    id: "34",
    name: "Sweet Potato",
    tamilName: "சர்க்கரைவள்ளி கிழங்கு",
    image: "local://Potato.png",
    price: 45,
    origin: "Southern States",
  },
  {
    id: "35",
    name: "Small Onion",
    tamilName: "சின்ன வெங்காயம்",
    image: "local://Onion.png",
    price: 80,
    origin: "Southern States",
  },
  {
    id: "36",
    name: "Coconut",
    tamilName: "தேங்காய்",
    image: "local://Coconut.png",
    price: 30, // Per piece
    origin: "Southern States",
  },
  {
    id: "37",
    name: "Green Mango",
    tamilName: "மாங்காய்",
    image: "local://RawMango.png",
    price: 60,
    origin: "Southern States",
  },
  {
    id: "38",
    name: "Broad Beans (Valpandal)",
    tamilName: "அவரைக்காய்",
    image: "local://Beans.png",
    price: 55,
    origin: "Southern States",
  },
  {
    id: "39",
    name: "Mushroom",
    tamilName: "காளான்",
    image: "local://Mushroom.png",
    price: 40, // Per pack
    origin: "Southern States",
  },
  {
    id: "40",
    name: "Spring Onion",
    tamilName: "வெங்காயத்தாள்",
    image: "local://Greens.png",
    price: 20,
    origin: "Southern States",
  },
];
